<?php
/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Magento\Framework\Escaper $escaper */
?>

<div class="custom-wishlist-container" data-bind="scope: 'custom-wishlist'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>


<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "custom-wishlist": {
                        "component": "Magento_Wishlist/js/view/custom-wishlist",
                        "wishlistUrl": "<?= $block->getUrl('wishlist') ?>"
                    }
                }
            }
        }
    }
</script>
