<?php
/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Magento\Framework\Escaper $escaper */
?>

<h3>Search Country</h3>
<p id="error-message"></p>
<form id="search-country-form" data-mage-init='{"validation": {}}'>
    <label for="country-id">Country ID</label>
    <input type="text" name="country-id" id="country-id" class="country-id" data-validate="{'validate-country-id':true}" placeholder="Country ID..."/>
    <button type="submit">Search</button>
</form>

<div>
    <p id="country-name"></p>
</div>


<script type="text/x-magento-init">
    {
        "#search-country-form": {
            "Magento_Cms/js/custom-country-form": {}
        }
    }
</script>
