<?php
/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Magento\Framework\Escaper $escaper */
?>
<h2>First Custom Form</h2>
<form id="custom-coupon-form" data-mage-init='{"validation":{}}'>
    <label for="coupon-abc-123">Format: ABC-123</label>
    <input name="coupon-abc-123" id="coupon-abc-123" data-validate='{"validate-coupon-abc-123":true}' placeholder="ABC-123">
    <label for="coupon-abc-abc">Format: ABC-ABC</label>
    <input name="coupon-abc-abc" id="coupon-abc-abc" data-validate='{"validate-coupon-abc-abc":true}' placeholder="ABC-ABC">
    <label for="coupon-123-123">Format: 123-123</label>
    <input name="coupon-123-123" id="coupon-123-123" data-validate='{"validate-coupon-123-123":true}' placeholder="123-123">
    <button type="submit">Send</button>
</form>
