name: Deploy Gustav theme on VPS

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check for JS files
        run: |
          countjs=$(find . -name '*.js' | wc -l)
          echo "Number of .js files: $countjs"
          echo "HAS_JS_FILES=$(( countjs > 0 ))" >> $GITHUB_ENV

      - name: Check for LESS and CSS files
        run: |
          countstyles=$(find . -name '*.less' -o -name '*.css' | wc -l)
          echo "Number of .less and .css files: $countstyles"
          echo "HAS_STYLES_FILES=$(( countstyles > 0 ))" >> $GITHUB_ENV

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
        if: ${{ env.HAS_JS_FILES == '1' || env.HAS_STYLES_FILES == '1' }}

      - name: Install dependencies from package-lock.json
        run: npm ci
        if: ${{ env.HAS_JS_FILES == '1' || env.HAS_STYLES_FILES == '1' }}

      - name: Run ESLint
        run: npm run eslint --if-present
        if: ${{ env.HAS_JS_FILES == '1' }}

      - name: Run Stylelint
        run: npm run stylelint --if-present
        if: ${{ env.HAS_STYLES_FILES == '1' }}

      - name: Run a build command
        uses: dawidd6/action-ansible-playbook@v2
        if: ${{ github.event.pull_request.merged == true }}
        with:
          playbook: .ansible/main.yml
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          inventory: |
            [all]
            ${{ secrets.VPS }} address=localhost
          options: |
            -e GITHUB_REPO=${{ github.repository }}
            -e ansible_port=${{ secrets.SSH_PORT }}
